language: node_js
node_js:
- '10'
dist: trusty
sudo: required
branches:
  only:
  - master
addons:
  ssh_known_hosts: "vm.cerberus-testing.org"
before_script:
- npm install -g @angular/cli
script:
- ng lint
- ng build --prod
before_deploy:
- openssl aes-256-cbc -K $encrypted_46e7356b76be_key -iv $encrypted_46e7356b76be_iv  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  skip_cleanup: true
  provider: script
  script: sh ./deploy/scripts/deploy.sh
  on:
    branch: master
